sudo: required
before_install:
  - sudo add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq qt5-qmake qtbase5-dev qt5-default qttools5-dev-tools libqt5serialport5-dev

language: cpp

# Compiler selection
compiler:
  - gcc

install: true

env:
  - TEST=tools

# Build steps
script:
  - make $TEST
